language: node_js
node_js:
  - '7'
branches:
  only:
    - master
before_script:
  - npm install
script:
  - gatsby build
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master
env:
  global:
    - secure: "UGPt1SFB1Be9xT6J6z5T0z+OWjeQZxTimLYC+4/qCjMlAVzqkgIpiPLGor9EzKZ1FtNe7oSxE9Rn/O0976c8ROzejqO3BfPIh490nTeIcQPwHdx6wcYFJrtqYzAFYE3mBVj0GI8dpIohPJaGqh+i1xguU5qgDZWW20XObmQk6JrKdfqjTlbfeMqEdZn6xEMp84+pWkHvQbOA+LA5i5dnBfdEr1vUNaVE8vx73r1zLHid4eckqCIUxSKgu9sj4ceOO8S1lYhTCAOGsEoVRBLauj23HR7Ucs9kBOik2GPIOgAN6+7E2fymZ83ulhV26XbDZdlFw7QURn5kmZc6/QfGHIifdfPlFoeCCM7RIZOqgH7AA8iHrp+NUMSDx5SaEwUR6kkjnAfpxBiPcDFkJMdNB/ah6QnRuyiK5GiYOQF///6958Gcx2sqwlt/yyZV4OOvbIIrUVjJefUNvWeNOyKEy5LsxmspbBROqFCqHV5TX4oZRx7osQrYXuPtzsjxtBU71KviXLWUMaE1X4ZLvwpvgj5PcnyWbAIzRALlnGMJAGE5omnchYse10MLX3DS/Hcskwnarw9+kLjP+6gVpaFjxHQqW8AaHhJifNxvXwg5GnZ4cFJpQfR88p//Bg27uXH64RO+BXAUiwQ5h8BX8cQln32Txx6JuMO7Ltp6zsQoopI="
