language: node_js
node_js:
  - iojs
  - '7'
branches:
  only:
    - master
before_script:
  - npm install
script:
  - gatsby build
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
    - secure: Qf6JjerBciZJSctmhncZapwzq2LBXSSHRYRSp44h2tAmTkC8C9o7+DTjJlTU0Mxp4yJMyfcITjSdaHA3Nd8yVc55SgvHMHGs39d+pBZ06cE+r4wTMcL0uvved8/IVl8n8TNs5lwK6szEaI5JPBko4+p4HipKTu9F8OFVxKsstds8zPd/ShiNGS2Dp4DXaRl9PNKMEDCTDYYY2WIT9ZaJMhKMa5CN1C2mwxGxbVr1EqkJT+zEKkelAddM2A1O2ETTt60gyAy2Zz03rOuEKAKjJau5USgzP3pv4EXnAm3fjMp0RAPner3h1OdgQzbeEsEqPWni/bNO26Ojdcx0dIFbQJyR7XOjzyNthau4MMy6tSiPM30HRKmA1PMl5jHUJnXRE1cxDK7/YomHl6H7e1vgeTgfG3Rk0JlPpDnGWWwWLdbK7r5mULh/rbOp7IbO052u1bV0oAgFotQVUvLw5w7oxbiKNhc6nNqqchdaeOOTUOd+bj7LruIYAP56NUWrCUZAOeSCsdrcY5rrMsuiD7LyD5Eg0hPG25bHCUBkhOIMga+5i52F0OL9kZBCo5NIprEIpEYsWoE9vJmnEabzFMdjBiNnUJKxV7LaO4AVIyt1swYxEKZ7UyGR6bMICpra7SHi3xuebdrrr1BIXp0tqRI69J1PVjXYPC2XIznP8hz5ebw=
